version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Add other environment variables here
      # - SUPABASE_URL=your_supabase_url
      # - SUPABASE_KEY=your_supabase_key
    restart: unless-stopped
    # If you need to persist data, uncomment and configure volumes
    # volumes:
    #   - ./data:/app/data