name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 134.199.145.43
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/workspace/propelity-be
            git pull
            
            # Ensure docker-compose is installed
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing docker-compose..."
              apt-get update
              apt-get install -y docker-compose
            fi
            
            # Make the scripts executable
            chmod +x docker-build.sh docker-run.sh
            
            # Build and run the application, capture output
            OUTPUT=$(./docker-build.sh && ./docker-run.sh 2>&1)
            echo "$OUTPUT"
            
            # Check if deployment was successful
            if ! echo "$OUTPUT" | grep -q "Containers started successfully. The application is available at http://localhost:3000"; then
              echo "Deployment failed: Success message not found in output"
              exit 1
            fi