name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 134.199.145.43
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/workspace/propelity-be
            git pull
            
            # Ensure docker-compose is installed
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing docker-compose..."
              apt-get update
              apt-get install -y docker-compose
            fi
            
            # Use the new deployment script
            chmod +x deploy.sh
            ./deploy.sh
            
            # Verify service is running
            echo "Verifying service status..."
            docker-compose ps
            
            # Test email if needed (uncomment if you want to test emails on every deploy)
            # ./deploy.sh --test-email 