name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 134.199.145.43
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/workspace/propelity-be
            git pull
            
            # Ensure docker-compose is installed
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing docker-compose..."
              apt-get update
              apt-get install -y docker-compose
            fi
            
            # Make the scripts executable
            chmod +x deploy.sh
            
            # Try host network mode first
            echo "Deploying with host network mode for better connectivity..."
            ./deploy.sh --host-network --network-test
            
            # Check if email sending works
            echo "Testing email connectivity..."
            if ! docker-compose exec -T app node src/network-test.js | grep -q "✅ Success: Connected to smtp.zoho.com.au:465"; then
              echo "WARNING: Could not connect to SMTP server - trying alternative network configuration..."
              # Try default bridge network as fallback
              ./deploy.sh --network-test
            fi
            
            # Verify service is running
            echo "Verifying service status..."
            docker-compose ps
            
            # Final email test
            echo "Running final email test..."
            docker-compose exec -T app node src/docker-test-email.js || echo "Email test failed, but deployment continues"